name: Release binaries

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  test:
    name: Test release
    uses: EduardoNGomes/shared-workflows/.github/workflows/go-test-simple.yml@main

  release:
    name: Build and publish release
    needs: test
    permissions:
      contents: write
    uses: EduardoNGomes/shared-workflows/.github/workflows/go-os-build.yml@main
    with:
      name: mdo
